#!/bin/bash

echo "Criando diretórios...."
mkdir /publica
mkdir /adm
mkdir /ven
mkdir /sec

echo "Criando grupos de usuários...."
groupadd GRP_ADM
groupadd GRP_VEN
groupadd GRP_SEC

echo "Criando usuários...."
useradd carlos -c "Carlos da Silva" -m -s /bin/bash -G GRP_ADM
useradd maria -c "Maria de Lourdes" -m -s /bin/bash -G GRP_ADM
useradd joao -c "João Paulo" -m -s /bin/bash -G GRP_ADM
useradd debora -c "Debora Arrais" -m -s /bin/bash -G GRP_VEN
useradd sebastiana -c "Sebastiana Fidellis" -m -s /bin/bash -G GRP_VEN
useradd roberto -c "Roberto Carlos" -m -s /bin/bash -G GRP_VEN
useradd josefina -c "Josefina Damaceno" -m -s /bin/bash -G GRP_SEC
useradd amanda -c "Amanda Cabral" -m -s /bin/bash -G GRP_SEC
useradd rogerio -c "Rogério Tostes" -m -s /bin/bash -G GRP_SEC

echo "Especificando permissões dos diretórios...."
chown root:GRP_ADM /adm
chown root:GRP_VEN /ven
chown root:GRP_SEC /sec

chmod 770 /adm
chmod 770 /ven
chmod 770 /sec
chmod 777 /publica

echo "Fim...."
